# Generated by Django 5.1.14 on 2025-11-24 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_servicio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('tipos_servicio', models.JSONField(blank=True, default=list, null=True)),
                ('tipo_servicio_otro', models.CharField(blank=True, max_length=200, null=True)),
                ('ingeniero_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Ticket')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('actividades', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('horas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('costo_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_no_aplica', models.BooleanField(default=False)),
                ('costo_se_cotizara', models.BooleanField(default=False)),
                ('reagenda', models.BooleanField(default=False)),
                ('reagenda_fecha', models.DateField(blank=True, null=True)),
                ('reagenda_hora', models.TimeField(blank=True, null=True)),
                ('reagenda_motivo', models.TextField(blank=True)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('indicaciones_especiales', models.TextField(blank=True, help_text='Indicaciones internas. No se imprime.')),
                ('estatus', models.CharField(choices=[('borrador', 'En Pausa (Borrador)'), ('finalizado', 'Finalizado')], default='borrador', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('email_enviado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EngineerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='engineer_signatures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.CharField(max_length=200)),
                ('comentarios', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='orders.serviceorder')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='orders.serviceorder')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=100, verbose_name='Serie')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='orders.serviceorder')),
            ],
        ),
        migrations.CreateModel(
            name='ShelterEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('comentarios', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resguardos', to='orders.serviceorder')),
            ],
        ),
    ]
