# Generated by Django 5.1.13 on 2025-10-31 23:15

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio",
                    models.CharField(
                        default=orders.models.ServiceOrder.folio_default,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("cliente_nombre", models.CharField(max_length=200)),
                ("cliente_email", models.EmailField(blank=True, max_length=254)),
                ("ubicacion", models.CharField(blank=True, max_length=300)),
                ("fecha_servicio", models.DateField(default=django.utils.timezone.now)),
                ("contacto_nombre", models.CharField(blank=True, max_length=200)),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("instalacion", "Instalación"),
                            ("configuracion", "Configuración"),
                            ("mantenimiento", "Mantenimiento"),
                            ("garantia", "Garantía"),
                            ("revision", "Falla/Revisión"),
                            ("capacitacion", "Capacitación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ingeniero_nombre", models.CharField(max_length=200)),
                ("equipo_marca", models.CharField(blank=True, max_length=100)),
                ("equipo_modelo", models.CharField(blank=True, max_length=100)),
                ("equipo_serie", models.CharField(blank=True, max_length=100)),
                ("equipo_descripcion", models.TextField(blank=True)),
                ("titulo", models.CharField(max_length=250)),
                ("actividades", models.TextField(blank=True)),
                ("comentarios", models.TextField(blank=True)),
                (
                    "resguardo",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Ninguno / Adaptador / etc.",
                        max_length=200,
                    ),
                ),
                (
                    "horas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "costo_mxn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("costo_no_aplica", models.BooleanField(default=False)),
                ("costo_se_cotizara", models.BooleanField(default=False)),
                ("reagenda", models.BooleanField(default=False)),
                ("reagenda_fecha", models.DateField(blank=True, null=True)),
                ("reagenda_hora", models.TimeField(blank=True, null=True)),
                ("reagenda_motivo", models.TextField(blank=True)),
                (
                    "firma",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("email_enviado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("descripcion", models.CharField(max_length=200)),
                ("comentarios", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiales",
                        to="orders.serviceorder",
                    ),
                ),
            ],
        ),
    ]
