# Generated by Django 5.1.14 on 2025-11-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicematerial',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='cliente_contacto',
            field=models.CharField(blank=True, help_text='Nombre de la persona de contacto del cliente.', max_length=200, null=True),
        ),
    ]
