# Generated by Django 5.1.13 on 2025-11-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=100, verbose_name="Marca"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=100, verbose_name="Modelo"),
                ),
                (
                    "serie",
                    models.CharField(blank=True, max_length=100, verbose_name="Serie"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos",
                        to="orders.serviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["id"],
            },
        ),
    ]
