# Generated by Django 5.1.14 on 2026-01-02 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_serviceorder_visor_alter_servicematerial_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicematerial',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='indicaciones_especiales',
            field=models.TextField(blank=True, help_text='Indicaciones internas. No se imprime.'),
        ),
        migrations.CreateModel(
            name='TechnicalMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('contenido_v1_ia', models.TextField()),
                ('contenido_v2_user', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(related_name='memories', to='orders.serviceorder')),
            ],
        ),
    ]
