# Generated by Django 5.1.14 on 2025-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_servicematerial_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicematerial',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='cliente_contacto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
