# Generated by Django 5.1.14 on 2025-11-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_serviceorder_tipo_servicio_otro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='cliente_contacto',
            field=models.CharField(blank=True, help_text='Nombre de la persona de contacto del cliente.', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='cliente_telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del cliente.', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='indicaciones_especiales',
            field=models.TextField(blank=True, help_text='Indicaciones internas (EPP, credencial, pruebas, etc.). No se imprime.'),
        ),
    ]
