# Generated by Django 5.1.14 on 2025-11-28 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_servicematerial_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='visor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_visor', to=settings.AUTH_USER_MODEL, verbose_name='Contacto Ventas (Visor)'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto Interno (Texto)'),
        ),
    ]
