# Generated by Django 5.1.14 on 2025-11-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_serviceorder_cliente_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Ticket'),
        ),
    ]
