# Generated by Django 5.1.14 on 2025-11-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_serviceorder_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='equipo_descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='equipo_marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='equipo_modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='equipo_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
