# Generated by Django 5.1.14 on 2025-11-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_engineerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='equipo_descripcion',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='equipo_marca',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='equipo_modelo',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='equipo_serie',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='resguardo',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='estatus',
            field=models.CharField(choices=[('borrador', 'En Pausa (Borrador)'), ('finalizado', 'Finalizado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='indicaciones_especiales',
            field=models.TextField(blank=True, help_text='Indicaciones internas. No se imprime.'),
        ),
        migrations.CreateModel(
            name='ServiceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='orders.serviceorder')),
            ],
        ),
        migrations.CreateModel(
            name='ShelterEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.CharField(max_length=200)),
                ('comentarios', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resguardos', to='orders.serviceorder')),
            ],
        ),
    ]
