# Generated by Django 5.1.14 on 2025-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_equipment_options_remove_equipment_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterequipment',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shelterequipment',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
