# Generated by Django 5.1.14 on 2025-11-24 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_shelterequipment_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='cliente_contacto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='fecha_servicio',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='ingeniero_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Ticket'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='tipo_servicio_otro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='tipos_servicio',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='titulo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
